kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: maven-settings-pvc
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: gp2
  volumeMode: Filesystem

